### ISSUE TITLE
Feat(Cards): Individual card design for individual users

### ISSUE THREAD

**Issue by narainkarthikv** [narainkarthikv/contribution-cards#30]
**Tasks**
- [ ] Implement individual card designs for each user.
- [ ] Ensure cards are adaptable and responsive on all screen sizes.
- [ ] Provide a proper link for users to access and share their cards.
